from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

from langchain_core.tools import tool

try:
    from langchain_mcp_adapters.client import MultiServerMCPClient # type: ignore
except Exception:  # pragma: no cover
    MultiServerMCPClient = None


# ---------------------------------------------------------------------
# Project path helpers
# ---------------------------------------------------------------------
# This file lives at:
# backend/domain/tools/lifestore_mcp_tools.py
#
# Therefore:
# parents[0] = backend/domain/tools
# parents[1] = backend/domain
# parents[2] = backend
# parents[3] = project root
PROJECT_ROOT = Path(__file__).resolve().parents[3]
MCP_LAUNCHER_PATH = PROJECT_ROOT / "backend" / "services" / "lifestore_mcp_launcher.py"

_MCP_CLIENT: Any | None = None
_MCP_TOOLS_CACHE: dict[str, Any] | None = None


# ---------------------------------------------------------------------
# MCP client setup
# ---------------------------------------------------------------------
def _mcp_auth_headers() -> dict[str, str]:
    """
    Build optional authentication headers for backend -> MCP communication.

    In staging/production, set:
        LIFESTORE_MCP_TOKEN=<strong-random-token>

    The backend will send:
        Authorization: Bearer <token>

    If the token is not configured, no auth header is sent. This keeps local
    development flexible, while allowing secured staging/production deployments.
    """
    token = os.getenv("LIFESTORE_MCP_TOKEN", "").strip()

    if not token:
        return {}

    return {
        "Authorization": f"Bearer {token}",
    }


def _get_mcp_client() -> Any:
    """
    Create the real MCP client used by the LangGraph tool wrappers.

    Supports two production modes:
    1. stdio: backend launches the MCP server through lifestore_mcp_launcher.py
    2. streamable_http: backend connects to a persistent MCP server URL

    Security:
    - For streamable_http mode, if LIFESTORE_MCP_TOKEN is set, the backend sends
      it as a Bearer token to the MCP server.
    """
    global _MCP_CLIENT

    if MultiServerMCPClient is None:
        raise RuntimeError(
            "langchain_mcp_adapters is not installed. Run: "
            "pip install -U 'langchain-mcp-adapters>=0.3.0' 'mcp>=1.27,<2'"
        )

    if _MCP_CLIENT is not None:
        return _MCP_CLIENT

    transport = os.getenv("LIFESTORE_MCP_TRANSPORT", "stdio").strip().lower()

    if transport in {"streamable_http", "streamable-http", "http"}:
        mcp_url = os.getenv("LIFESTORE_MCP_URL", "http://127.0.0.1:8001/mcp").strip()

        server_config: dict[str, Any] = {
            "transport": "streamable_http",
            "url": mcp_url,
        }

        auth_headers = _mcp_auth_headers()
        if auth_headers:
            server_config["headers"] = auth_headers

        _MCP_CLIENT = MultiServerMCPClient(
            {
                "lifestore": server_config,
            }
        )
        return _MCP_CLIENT

    launcher = os.getenv("LIFESTORE_MCP_LAUNCHER", str(MCP_LAUNCHER_PATH))

    if not Path(launcher).exists():
        raise FileNotFoundError(f"LifeStore MCP launcher not found at: {launcher}")

    _MCP_CLIENT = MultiServerMCPClient(
        {
            "lifestore": {
                "transport": "stdio",
                "command": os.getenv("LIFESTORE_MCP_COMMAND", sys.executable),
                "args": [launcher],
            }
        }
    )

    return _MCP_CLIENT

async def _get_mcp_tool_map() -> dict[str, Any]:
    """
    Load MCP tools from the LifeStore MCP server and cache them.

    The returned tools are LangChain-compatible wrappers generated by
    langchain_mcp_adapters from the real MCP server.
    """
    global _MCP_TOOLS_CACHE

    if _MCP_TOOLS_CACHE is not None:
        return _MCP_TOOLS_CACHE

    client = _get_mcp_client()
    tools = await client.get_tools()

    _MCP_TOOLS_CACHE = {item.name: item for item in tools}
    return _MCP_TOOLS_CACHE


def _safe_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _json_default(value: Any) -> str:
    try:
        return str(value)
    except Exception:
        return "<unserializable>"


def _limit_text(value: Any, max_chars: int = 700) -> str:
    text = _safe_text(value)
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip() + "..."


def _extract_text_from_content_block(block: Any) -> str:
    """
    MCP adapter results can be plain strings, dicts, content blocks, or objects.
    This makes the result parsing defensive.
    """
    if block is None:
        return ""

    if isinstance(block, str):
        return block

    if isinstance(block, dict):
        for key in ["text", "content", "value", "result"]:
            if key in block:
                return _safe_text(block.get(key))
        return json.dumps(block, ensure_ascii=False, default=_json_default)

    for attr in ["text", "content", "value"]:
        if hasattr(block, attr):
            return _safe_text(getattr(block, attr))

    return _safe_text(block)


def _try_parse_json_text(text: str) -> Any:
    text = _safe_text(text)

    if not text:
        return None

    try:
        return json.loads(text)
    except Exception:
        pass

    # Some tool wrappers may return readable text around JSON.
    start = text.find("{")
    end = text.rfind("}")

    if start >= 0 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except Exception:
            return None

    return None


def _coerce_mcp_result(raw: Any) -> dict[str, Any]:
    """
    Convert a raw MCP adapter return value into a dictionary.
    """
    if isinstance(raw, dict):
        return raw

    if isinstance(raw, list):
        joined = "\n".join(
            part
            for part in (_extract_text_from_content_block(item) for item in raw)
            if part
        )
        parsed = _try_parse_json_text(joined)
        if isinstance(parsed, dict):
            return parsed
        return {"status": "success", "text": joined, "raw_result": joined}

    parsed = _try_parse_json_text(_extract_text_from_content_block(raw))
    if isinstance(parsed, dict):
        return parsed

    return {
        "status": "success",
        "text": _extract_text_from_content_block(raw),
        "raw_result": _extract_text_from_content_block(raw),
    }


async def _call_mcp_tool(tool_name: str, **kwargs: Any) -> dict[str, Any]:
    """
    Call a real MCP server tool through langchain_mcp_adapters.

    This is the key Option B change:
    - No importlib
    - No direct Python function call
    - Tool call goes through MCP client -> MCP server -> tool
    """
    try:
        tool_map = await _get_mcp_tool_map()
        mcp_tool = tool_map.get(tool_name)

        if mcp_tool is None:
            return {
                "status": "error",
                "message": f"MCP tool '{tool_name}' was not found on the LifeStore MCP server.",
                "available_tools": sorted(tool_map.keys()),
            }

        raw_result = await mcp_tool.ainvoke(kwargs)
        result = _coerce_mcp_result(raw_result)

        if "status" not in result:
            result["status"] = "success"

        return result

    except Exception as exc:
        return {
            "status": "error",
            "message": str(exc),
            "tool_name": tool_name,
            "mcp_launcher_path": str(MCP_LAUNCHER_PATH),
        }


# ---------------------------------------------------------------------
# JSON / output compaction helpers
# ---------------------------------------------------------------------
def _compact_product(product: dict[str, Any]) -> dict[str, Any]:
    """
    Keep only the fields the LLM needs to answer safely.

    This prevents ToolNode from sending huge raw product payloads back into
    the model and reduces the chance of mixed-up product details.
    """
    key_details = product.get("key_details") or []
    if not isinstance(key_details, list):
        key_details = []

    vector_evidence = product.get("vector_evidence") or []
    if not isinstance(vector_evidence, list):
        vector_evidence = []

    compact = {
        "product_id": product.get("product_id"),
        "name": product.get("name"),
        "seller": product.get("seller"),
        "brand": product.get("brand"),
        "category": product.get("category"),
        "product_type": product.get("product_type"),
        "price": product.get("price"),
        "price_value": product.get("price_value"),
        "currency": product.get("currency"),
        "stock_status": product.get("stock_status") or product.get("availability"),
        "stock": product.get("stock"),
        "url": product.get("url"),
        "image_url": product.get("image_url"),
        "image_available": product.get("image_available"),
        "image_source": product.get("image_source"),
        "description": _limit_text(product.get("description"), 700),
        "key_details": [_limit_text(item, 220) for item in key_details[:6]],
        "vector_evidence": [_limit_text(item, 500) for item in vector_evidence[:3]],
    }

    return {
        key: value
        for key, value in compact.items()
        if value not in (None, "", [], {})
    }



BAD_PRODUCT_CARD_IMAGE_MARKERS = {
    "970_90",
    "inline-images/970_90",
    "eteleshop",
    "teleshop",
    "/themes/shop/images/",
    "union-pay",
    "visa",
    "master",
    "mastercard",
    "american",
    "payment",
    "payhere",
    "logo",
    "sltmobitel",
    "slt-mobitel",
    "chat",
    "chatbot",
    "footer",
    "header",
    "banner",
    "sprite",
    "loader",
    "ajax-loader",
    "placeholder",
    "default-image",
    "no-image",
}


def _is_valid_product_card_image(product: dict[str, Any]) -> bool:
    url = _safe_text(product.get("image_url")).lower()

    if not url.startswith(("http://", "https://")):
        return False

    if url.endswith(".svg") or url.startswith("data:"):
        return False

    if any(marker in url for marker in BAD_PRODUCT_CARD_IMAGE_MARKERS):
        return False

    return "/sites/default/files/" in url or any(
        ext in url for ext in [".jpg", ".jpeg", ".png", ".webp", ".gif"]
    )


def _infer_display_mode(result: dict[str, Any], products: list[dict[str, Any]]) -> str:
    frontend_contract = result.get("frontend_contract")
    if isinstance(frontend_contract, dict):
        display = _safe_text(frontend_contract.get("display"))
        render_as = _safe_text(frontend_contract.get("render_as")).lower()
        if display:
            return display
        if "comparison" in render_as:
            return "comparison"

    if len(products) <= 1:
        return "single"
    return "carousel"


def _build_product_cards(products: list[dict[str, Any]], limit: int) -> list[dict[str, Any]]:
    cards: list[dict[str, Any]] = []
    for product in products:
        if _is_valid_product_card_image(product):
            cards.append(product)
        if len(cards) >= max(int(limit), 1):
            break
    return cards

def _extract_products(result: dict[str, Any], limit: int = 5) -> list[dict[str, Any]]:
    """
    MCP tools may return products in different shapes:
    - products
    - returned_products
    - product
    - order.items
    """
    if int(limit or 0) <= 0:
        return []

    products: list[dict[str, Any]] = []

    raw_products = result.get("products")
    if isinstance(raw_products, list):
        products.extend(item for item in raw_products if isinstance(item, dict))

    returned_products = result.get("returned_products")
    if isinstance(returned_products, list):
        products.extend(item for item in returned_products if isinstance(item, dict))

    single_product = result.get("product")
    if isinstance(single_product, dict):
        products.append(single_product)

    order = result.get("order")
    if isinstance(order, dict):
        order_items = order.get("items")
        if isinstance(order_items, list):
            products.extend(item for item in order_items if isinstance(item, dict))

    deduped: list[dict[str, Any]] = []
    seen: set[str] = set()

    for product in products:
        key = (
            _safe_text(product.get("url"))
            or _safe_text(product.get("product_id"))
            or _safe_text(product.get("name")).lower()
        )

        if not key or key in seen:
            continue

        seen.add(key)
        deduped.append(_compact_product(product))

        if len(deduped) >= max(int(limit), 1):
            break

    return deduped


def _compact_result(
    result: dict[str, Any],
    *,
    product_limit: int = 5,
    include_answer: bool = True,
    include_categories: bool = False,
) -> dict[str, Any]:
    """
    Normalize MCP responses into a compact structure for the LLM.

    Important frontend rule:
    - `products` is the source for the visible answer/table.
    - `product_cards` is the image-safe subset the LLM should place inside
      [LIFESTORE_PRODUCT_CARDS] so broad queries still render a slideshow.
    """
    compact: dict[str, Any] = {
        "status": result.get("status"),
        "message": result.get("message"),
        "text": result.get("text"),
        "query": result.get("query"),
        "retrieval_query": result.get("retrieval_query"),
        "product_query": result.get("product_query"),
        "requested_availability": result.get("requested_availability"),
        "actual_availability": result.get("actual_availability"),
        "matches_requested_availability": result.get("matches_requested_availability"),
        "retrieval": result.get("retrieval"),
    }

    if include_answer:
        compact["answer"] = _limit_text(result.get("answer"), 1800)

    products = _extract_products(result, limit=product_limit)
    if products:
        display = _infer_display_mode(result, products)
        product_cards = _build_product_cards(products, limit=product_limit)

        compact["products"] = products
        compact["display"] = display
        compact["product_cards"] = product_cards
        compact["product_card_instruction"] = (
            "If product_cards is non-empty, always append a hidden "
            "[LIFESTORE_PRODUCT_CARDS] block using product_cards. "
            "Use display as the block display value. The visible table must use "
            "the same final products list returned by the MCP tool; do not add "
            "extra semantic matches or accessories that are not in products."
        )

    if include_categories:
        categories = result.get("categories")
        if isinstance(categories, list):
            compact["categories"] = categories[:80]

    frontend_contract = result.get("frontend_contract")
    if isinstance(frontend_contract, dict):
        compact["frontend_contract"] = frontend_contract

    return {
        key: value
        for key, value in compact.items()
        if value not in (None, "", [], {})
    }


def _to_tool_json(payload: dict[str, Any]) -> str:
    """
    LangGraph ToolNode sends tool results back to the LLM as ToolMessages.
    Returning JSON text keeps the result readable and predictable.
    """
    return json.dumps(payload, ensure_ascii=False, indent=2, default=_json_default)


def _parse_product_queries(product_queries: str) -> list[str]:
    """
    Accept either:
    - JSON list: ["Product A", "Product B"]
    - comma-separated text: Product A, Product B
    """
    text = _safe_text(product_queries)

    if not text:
        return []

    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            return [_safe_text(item) for item in parsed if _safe_text(item)]
    except Exception:
        pass

    return [_safe_text(item) for item in text.split(",") if _safe_text(item)]


# ---------------------------------------------------------------------
# LangGraph/LangChain tool wrappers
# ---------------------------------------------------------------------
@tool
async def lifestore_hybrid_product_search_tool(
    query: str,
    limit: int = 5,
    include_vector_evidence: bool = False,
    search_mode: str = "auto",
    product_query: str = "",
) -> str:
    """
    Search LifeStore products through the LifeStore MCP server.

    Use this for broad LifeStore product searches, category browsing,
    recommendations, and general product questions.
    """
    bounded_limit = max(min(int(limit or 8), 24), 1)

    result = await _call_mcp_tool(
        "lifestore_hybrid_product_search",
        query=query,
        limit=bounded_limit,
        include_vector_evidence=include_vector_evidence,
        search_mode=search_mode,
        product_query=product_query or None,
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=bounded_limit,
            include_answer=True,
        )
    )


@tool
async def lifestore_precise_product_lookup_tool(
    product_query: str,
    include_vector_evidence: bool = False,
) -> str:
    """
    Look up one specific LifeStore product through the LifeStore MCP server.

    Use this when the user asks about one named product, product ID, SKU, or URL.
    """
    result = await _call_mcp_tool(
        "lifestore_precise_product_lookup",
        product_query=product_query,
        include_vector_evidence=include_vector_evidence,
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=1,
            include_answer=True,
        )
    )


@tool
async def lifestore_availability_lookup_tool(
    product_query: str,
    requested_availability: str = "in_stock",
) -> str:
    """
    Check availability for one specific LifeStore product through the MCP server.

    Use this for direct stock or availability questions.
    """
    result = await _call_mcp_tool(
        "lifestore_availability_lookup",
        product_query=product_query,
        requested_availability=requested_availability,
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=1,
            include_answer=False,
        )
    )


@tool
async def lifestore_compare_products_tool(
    query: str,
    product_queries: str = "",
    limit: int = 4,
    include_vector_evidence: bool = False,
) -> str:
    """
    Compare LifeStore products through the LifeStore MCP server.

    product_queries can be either:
    - JSON list string: ["Product A", "Product B"]
    - comma-separated string: Product A, Product B
    """
    bounded_limit = max(min(int(limit or 4), 6), 2)
    parsed_product_queries = _parse_product_queries(product_queries)

    result = await _call_mcp_tool(
        "lifestore_compare_products",
        query=query,
        product_queries=parsed_product_queries if parsed_product_queries else None,
        limit=bounded_limit,
        include_vector_evidence=include_vector_evidence,
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=bounded_limit,
            include_answer=True,
        )
    )


@tool
async def lifestore_filtered_product_search_tool(
    query: str,
    category: str = "",
    min_price: float | None = None,
    max_price: float | None = None,
    in_stock_only: bool = False,
    sort: str = "relevance",
    limit: int = 5,
) -> str:
    """
    Search LifeStore products with exact filters through the MCP server.

    Use this when the user asks for:
    - available products
    - in-stock products
    - products under/above a price
    - products in a category
    - sorted product lists

    For questions like "Show me available routers", set:
    in_stock_only=True
    query="router"
    """
    bounded_limit = max(min(int(limit or 8), 24), 1)

    result = await _call_mcp_tool(
        "lifestore_search_products",
        q=query,
        category=category or None,
        min_price=min_price,
        max_price=max_price,
        in_stock_only=in_stock_only,
        sort=sort,
        limit=bounded_limit,
        cursor=0,
        currency="LKR",
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=bounded_limit,
            include_answer=False,
        )
    )


@tool
async def lifestore_strict_category_products_tool(
    category: str,
    in_stock_only: bool = False,
    limit: int = 12,
) -> str:
    """
    Return exact LifeStore category/offer products through the MCP server.

    Use this for exact category/offer questions:
    - Special Offers
    - New Connection Offers
    - Bundle Offers
    - specially offered items

    This avoids Qdrant semantic matches and returns only products that have the
    requested category/offer label in the product data.
    """
    bounded_limit = max(min(int(limit or 12), 24), 1)

    result = await _call_mcp_tool(
        "lifestore_strict_category_products",
        category=category,
        in_stock_only=in_stock_only,
        limit=bounded_limit,
        currency="LKR",
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=bounded_limit,
            include_answer=False,
        )
    )


@tool
async def lifestore_list_categories_tool(depth: int = 1) -> str:
    """
    List LifeStore product categories through the LifeStore MCP server.
    """
    result = await _call_mcp_tool(
        "lifestore_list_categories",
        depth=depth,
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=0,
            include_answer=False,
            include_categories=True,
        )
    )


@tool
async def lifestore_create_draft_order_tool(
    cart_json: str,
    currency: str = "LKR",
) -> str:
    """
    Create a local LifeStore draft order through the LifeStore MCP server.

    Use this only when the user has clearly selected product(s) and wants to
    proceed with an order. This does not place a real order and does not create
    a real payment link.

    cart_json should be a JSON list:
    [
      {"name": "COMSTOX ZLT T10 Max 4G LTE Router", "quantity": 1}
    ]
    """
    try:
        cart = json.loads(cart_json)
    except Exception:
        return _to_tool_json(
            {
                "status": "invalid_cart_json",
                "message": "cart_json must be a valid JSON list of cart items.",
            }
        )

    result = await _call_mcp_tool(
        "lifestore_create_order",
        cart=cart,
        currency=currency,
    )

    return _to_tool_json(
        _compact_result(
            result,
            product_limit=8,
            include_answer=False,
        )
    )


LIFESTORE_MCP_TOOLS = [
    lifestore_filtered_product_search_tool,
    lifestore_strict_category_products_tool,
    lifestore_hybrid_product_search_tool,
    lifestore_precise_product_lookup_tool,
    lifestore_availability_lookup_tool,
    lifestore_compare_products_tool,
    lifestore_list_categories_tool,
    lifestore_create_draft_order_tool,
]
