version: '3.8'

services:
  db_postgres:
    image: ankane/pgvector:latest
    container_name: slt_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: slt
      POSTGRES_PASSWORD: slt123
      POSTGRES_DB: slt_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  db_qdrant:
    image: qdrant/qdrant:latest
    container_name: slt_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: always

  backend:
    build:
      context: ./backend
    container_name: slt_backend
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
      - db_qdrant
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_URL: postgresql://slt:slt123@db_postgres:5432/slt_db
      QDRANT_URL: http://slt_qdrant:6333
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: slt_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
