"""Routing profiles and thresholds for the Ask SLT supervisor agent.

This module keeps the specialist routing metadata separate from the supervisor
implementation so the routing surface can be tuned later without rewriting the
agent logic.
"""

from __future__ import annotations

SPECIALIST_ROUTING_PROFILES: dict[str, dict[str, object]] = {
    "hr": {
        "display_name": "HR",
        "description": (
            "This domain handles employee-related matters at SLTMobitel, including "
            "attendance marking, various leave types (annual, casual, sick, maternity, "
            "overseas), and contract employment administration. It also covers employee "
            "benefits and financial support like medical claims (including Agrahara) and "
            "staff loans, as well as performance management, grievance handling, and "
            "workplace policies such as digital media usage."
        ),
        "keywords": [
            "apply for leave",
            "leave balance",
            "annual leave",
            "casual leave",
            "sick leave",
            "medical leave",
            "half day leave",
            "short leave",
            "maternity leave",
            "child care leave",
            "accident leave",
            "overseas leave",
            "mark attendance",
            "finger scan machine",
            "late attendance",
            "unauthorized absence",
            "ERP leave system",
            "distress loan",
            "motorcycle loan",
            "motor car loan",
            "TDC education loan",
            "loan guarantor",
            "top up loan",
            "loan interest rate",
            "medical claim",
            "Agrahara reimbursement",
            "spectacles claim",
            "dental claim",
            "hospitalization benefit",
            "critical illness benefit",
            "add dependents ERP",
            "performance appraisal",
            "KPI targets",
            "mid-year review",
            "peer evaluation",
            "fairness review committee",
            "annual bonus",
            "salary",
            "loan",
            "file a grievance",
            "grievance handling committee",
            "vacation of post",
            "VOP",
            "probation period",
            "EPF",
            "ETF",
            "digital media policy",
            "social media rules",
        ],
        "examples": [
            "How do I apply for annual leave in the ERP system?",
            "What is the policy for taking an afternoon half-day leave?",
            "Where can I find the application for a distress loan?",
            "How many sick leave days do I get in my first year of probation?",
            "Can I apply for a motorcycle loan if I don't have 5 years of service?",
            "How do I claim reimbursement for my new spectacles?",
            "What documents are needed to apply for the critical illness medical benefit?",
            "How do I add my spouse and newborn child to the Agrahara medical benefits?",
            "What is the process for the mid-year performance review discussion?",
            "How are individual KPI targets set and updated in the ERP system?",
            "What should I do if I have a grievance with my manager regarding my performance rating?",
            "Am I allowed to post about SLTMobitel on my personal Facebook account?",
            "What is the disciplinary penalty for unauthorized absence from work?",
            "How do I apply for overseas no-pay leave for higher studies?",
            "Does my contract employment include EPF and ETF contributions?",
            "What happens to my unutilized earned leave when my contract ends?",
            "What is the maximum amount I can get for the TDC education loan?",
            "Where do I submit the valuation report for a used motor car loan?",
        ],
    },
    "finance": {
        "display_name": "Finance",
        "description": (
            "Handles corporate finance operations including AP invoice processing, "
            "CAPEX budgeting, advance payments, taxation (VAT, WHT, NBT), and "
            "financial reporting under SLFRS. Manages billing dispute resolution "
            "and adjustment approvals through committees like MDRC, CDRTF, CDRAC, "
            "PDRC, and BAAC according to delegated financial authority limits. "
            "Oversees bank reconciliation, cash handling, vendor payments via EFT "
            "or cheque, and ERP General Ledger maintenance."
        ),
        "keywords": [
            "MDRC",
            "CDRTF",
            "CDRAC",
            "PDRC",
            "BAAC",
            "VAT",
            "WHT",
            "NBT",
            "SLFRS",
            "AP Invoice",
            "Batta payment",
            "Work Confirmation",
            "Purchase Order",
            "PO matching",
            "GRN",
            "CAPEX Budget",
            "advance payment",
            "advance settlement",
            "billing dispute",
            "bill adjustment",
            "sales reversal",
            "credit memo",
            "debit memo",
            "bank reconciliation",
            "cash forecasting",
            "mCash refund",
            "Geneva adjustment",
            "Delegation of Financial Authority",
            "Junior Tender Board",
            "Senior Tender Board",
            "Letter of Credit",
            "LC payment",
            "General Ledger",
            "Trial Balance",
            "telecommunication levy",
            "CPE recovery",
            "Manual Receipt",
            "EFT payment",
            "debt collecting company",
            "manual invoice",
        ],
        "examples": [
            "What are the role and responsibilities of MDRC?",
            "Who approves an MSME dispute adjustment limit above 50,000 for the MDRC team?",
            "How do I record a corporate billing dispute for the CDRTF?",
            "What is the adjustment limit recommended by the CDRTF?",
            "Who sits on the Corporate Customers Dispute Resolution Adjustment Committee (CDRAC)?",
            "How does CDRAC handle billing adjustments over 1.5 million LKR?",
            "When should a regional dispute be forwarded to the PDRC?",
            "Who is the Co-Chairman of the PDRC?",
            "What is the adjustment approval limit for the BAAC?",
            "How do I submit a case to the Bill Adjustment Approval Committee (BAAC)?",
            "How do I process an AP Invoice matched to a Purchase Order?",
            "Where do I find the Advance Request Form and Advance Settlement Form?",
            "What is the procedure for an mCash refund?",
            "Who has the contract signing authority for non-standardized goods?",
            "How do I calculate WHT and VAT on a standard invoice?",
            "What is the ERP process for updating the General Ledger?",
            "How do I handle manual receipts if the cashiering system is down?",
            "What are the steps for a Letter of Credit (LC) payment?",
            "How do I handle CPE recovery for a customer with arrears over Rs. 10,000?",
            "Where do I apply for a CAPEX budget allocation for a new project?",
        ],
    },
    "admin": {
        "display_name": "Admin",
        "description": (
            "The Admin domain handles physical infrastructure, facilities "
            "management, and logistical operations, including power and AC "
            "maintenance, vehicle fleet management, parking allocation, and "
            "property leasing such as holiday bungalows. It oversees physical "
            "security, access control, visitor and gate passes, incident "
            "reporting, and fire safety (FAFA). Key services and assets are "
            "managed through bodies like the Transport Management Section, "
            "Property Management Team, Facility Management Section, and the "
            "Security Section."
        ),
        "keywords": [
            "office transport",
            "PickMe cab service facility",
            "hired vehicle allocation",
            "Self-Provided Vehicle Scheme",
            "vehicle tracking device",
            "e-running chart system",
            "driver's running record book",
            "vehicle in and out registry",
            "access control procedure",
            "visitor pass",
            "temporary electronic access card",
            "trainee pass",
            "gate pass form",
            "Item Declaration Form",
            "IDF",
            "SLTiDC",
            "children book",
            "visitor entry form",
            "security help desk",
            "incident management system",
            "daily occurrence book",
            "FAFA",
            "fire extinguisher refilling",
            "holiday bungalow tariff",
            "holiday bungalow booking",
            "property management",
            "third-party occupied spaces",
            "HQ vehicle parking",
            "Lotus Road parking",
            "Leisure parking",
            "green colour parking pass",
            "E pass and F pass",
            "DGM car park",
            "motor bicycle parking",
            "Power and AC Operations",
            "comfort AC",
            "precision AC",
            "UPS backup power",
            "backup generator",
            "surge protection devices",
            "SPD",
            "Facility Management Section",
            "Transport Management Section",
            "Property Management Team",
            "Security Section",
            "Document Preparation Committee",
        ],
        "examples": [
            "Where can I find the Item Declaration Form (IDF) for bringing in personal electronics?",
            "Who needs to sign the Item Declaration Form when I bring my camera to the office?",
            "How do I get a Gate pass form approved to take office equipment out of the building?",
            "What is the procedure for returning the original Gate pass form to the security officer?",
            "Where is the 'in and out' registry kept for hired vehicles?",
            "Does the security officer or the driver update the 'in and out' registry at the gate?",
            "How do I report a security incident for the daily occurrence book?",
            "Who checks the daily occurrence book for minor incidents?",
            "How does the Vehicle Officer in Charge certify invoices using the e-running chart system?",
            "What should I do if the e-running chart system fails during an official trip?",
            "Do I need to enter my relation's details in the children book at the reception desk?",
            "Is the children book mandatory for all visitors under 16 years old?",
            "Where do I submit a visitor entry form for a client meeting at HQ?",
            "Who approves the visitor entry form through the visitor management system?",
            "Who do I contact in the Transport Management Section for a PickMe cab facility?",
            "How does the Transport Management Section handle excess mileage payments for hired vehicles?",
            "How do I report a subsidiary occupied space to the Property Management Team?",
            "What details must be sent to the Property Management Team for billing rented spaces?",
            "Who approves new comfort AC installations in the Facility Management Section?",
            "Does the Facility Management Section handle pest control and elevator maintenance?",
            "How do I submit policy feedback to the Document Preparation Committee?",
            "Who leads the Document Preparation Committee for power and AC operational guidelines?",
        ],
    },
    "it": {
        "display_name": "IT",
        "description": (
            "The IT department manages corporate hardware (desktops, laptops, VDI thin "
            "clients, printers) and enterprise network connectivity (VPNs, firewalls, "
            "WiFi). It also handles user account provisioning, password resets, data "
            "security (DLP, backups, malware protection), and resolves IT service desk "
            "incidents like system outages or equipment damage."
        ),
        "keywords": [
            "password reset",
            "forgot password",
            "locked account",
            "unlock account",
            "domain password expired",
            "workflow manager request",
            "VPN connection",
            "VPN not working",
            "remote access",
            "site-to-site VPN",
            "extend VPN",
            "MFA",
            "laptop request",
            "desktop replacement",
            "broken laptop",
            "stolen laptop",
            "physical damage to PC",
            "hardware repair",
            "IT repair center",
            "new user account",
            "user registration",
            "deregister user",
            "transfer employee account",
            "VDI account",
            "VDI thin client",
            "work from home setup",
            "install software",
            "uninstall software",
            "trial software approval",
            "printer issue",
            "IT helpdesk",
            "report IT incident",
            "data backup",
            "restore data",
            "recover deleted file",
            "firewall rule change",
            "allow service",
            "block service",
            "WAF request",
            "USB drive blocked",
            "DLP alert",
            "data leakage",
            "report data breach",
            "wireless hotspot",
            "WiFi access",
            "network cable issue",
            "data center access",
            "ERP down",
            "CRM issue",
            "system outage",
        ],
        "examples": [
            "How do I request a new user account for a new employee through Workflow Manager?",
            "My domain password expired and my account is locked, how do I reset it?",
            "My corporate laptop is physically damaged, where do I take it for repair?",
            "How do I get a remote access VPN connection set up for working from home?",
            "I need to install some trial software on my official desktop, who do I contact?",
            "My VPN connection is expiring next week, how do I request an extension?",
            "I'm transferring to a different department, what do I do with my current IT accounts and PC?",
            "How do I request a firewall rule change to allow a new service through the network?",
            "I accidentally deleted a critical file, can you restore it from the backup?",
            "Why is my USB drive blocked when I try to copy files from my laptop?",
            "Where can I find the form to request physical access to the IT Data Center?",
            "What do I do if my official laptop or accessories are stolen?",
            "I need a VDI account and a thin client set up for a new call center user.",
            "Who do I contact to report a suspected data leakage or privacy incident?",
            "The ERP system seems to be down, is there a system outage right now?",
            "My office printer is not connecting to the network, can someone from the service desk help?",
            "How do I get approval to connect my mobile device to the corporate WiFi hotspot?",
        ],
    },
    "cia": {
        "display_name": "CIA",
        "description": (
            "Oversees corporate risk, internal controls, and compliance based on "
            "the Sri Lanka Telecom Internal Audit Charter. Key frameworks and "
            "governing bodies include the Enterprise Risk Management framework, "
            "the Group Audit Committee, the Audit Committee Terms of Reference, "
            "and the Code of Ethics and Standards of the Professional Practice "
            "of Internal Auditing."
        ),
        "keywords": [
            "Internal Audit Charter",
            "Group Audit Committee",
            "Enterprise Risk Management framework",
            "risk assessment",
            "risk management",
            "risk communication",
            "Audit Committee Terms of Reference",
            "Internal Audit Manual",
            "Code of Ethics and Standards of the Professional Practice of Internal Auditing",
            "Institute of Internal Auditors",
            "internal control systems",
            "governance processes",
            "fraud limitation",
            "ethical and legal compliance",
            "process improvement",
            "audit plan",
            "corporate risk profile",
            "management audits",
            "external audit reports",
            "intangible assets control",
        ],
        "examples": [
            "What is the policy for reviewing and updating the Internal Audit Charter?",
            "What does the Audit Committee Terms of Reference say about ethical and legal compliance?",
            "Who approves an exception to the annual Audit Plan?",
            "How often is the self-assessment of the Internal Audit activity done?",
            "What does the Enterprise Risk Management framework say about risk communication?",
            "Who is responsible for the identification and prevention of fraud under the charter?",
            "What is the established standard for the Internal Audit Manual?",
            "How often is an external assessment of the Internal Audit required?",
            "Who approves amendments to the Internal Audit Manual?",
            "What are management's responsibilities regarding internal controls and business risks?",
            "What is the governance process for safeguarding intangible assets?",
            "Who does the Group Chief Internal Auditor report to functionally and administratively?",
            "What does the Internal Audit Charter say about fraud limitation?",
            "What are the compliance requirements under the Code of Ethics and Standards?",
            "How often is the corporate risk profile updated?",
        ],
    },
    "network": {
        "display_name": "Network",
        "description": (
            "The Network domain covers the design, deployment, and operation of telecommunications "
            "infrastructure, including Core and Transport networks (MPLS, SDH, OTN, 100G core), Primary "
            "Access (LTE, CDMA, MSAN, OLT), and Secondary Fiber Access (FTTH passive ODN). It involves "
            "network service assurance (ENSA), fiber rollout procedures (FTC/FDP installation, OTDR "
            "testing), IP routing operations (OSPF, BGP, RSVP-TE, BRAS, VPNs), and 24/7 NOC/BBNOC "
            "monitoring of multi-vendor telecom equipment."
        ),
        "keywords": [
            "FTTH",
            "FTTx",
            "GPON",
            "MPLS",
            "SDH",
            "OTN",
            "100G core",
            "OSPF",
            "BGP",
            "LDP",
            "MP-BGP",
            "RSVP-TE",
            "FRR",
            "L2VPN",
            "L3VPN",
            "MVPN",
            "E2E QoS",
            "IP Multicasting",
            "IP Transit",
            "IX Peering",
            "5G",
            "LTE base stations",
            "CDMA base stations",
            "Core Fiber Network",
            "Fiber Termination Cabinet",
            "FTC",
            "Fiber Distribution Point",
            "FDP",
            "Optical Splitter",
            "Pigtails",
            "ODF",
            "MSAN",
            "OLT",
            "DSLAM",
            "BRAS",
            "CEA Aggregation Network",
            "L2 SSW",
            "L3 SW",
            "AGW",
            "Cable Landing Station",
            "ENSA",
            "NOC",
            "BBNOC",
            "OSS",
            "RFO Management",
            "Optical PAT",
            "OTDR test report",
            "Planned Event (PE)",
            "Huawei NCE",
            "Alcatel NSP NFM-P",
            "Cacti",
            "Netnumen",
        ],
        "examples": [
            "What is the procedure for terminating secondary cables in the Fiber Termination Cabinet (FTC)?",
            "How do we conduct an Optical PAT and generate the OTDR test report for the new fiber deployment?",
            "What is the minimum ground clearance and sag tolerance for aerial fiber cable drawing?",
            "How is MP-BGP and RSVP-TE configured on the new 100G core network nodes?",
            "What are the QoS and VLAN requirements for deploying a new L3VPN service?",
            "What is the ENSA fault escalation flow for a major D-PREMIUM VPN outage?",
            "Who handles maintenance and RFO management for the CEA Aggregation Network?",
            "What is the SLA for resolving a Tier III broadband fault at the BBNOC?",
            "How do we retrieve configuration backups for the Huawei NCE and Alcatel NSP NFM-P systems?",
            "Who is the platform engineer responsible for the Nokia MSAN/OLT platforms?",
            "What is the procedure for replacing a faulty optical splitter inside the ZTT Fiber Distribution Point (FDP)?",
            "How do we initiate a Planned Event (PE) in OSS for a Class A Core Fiber Network expansion?",
            "What is the approval workflow for drawing Class D Home Area Fiber to a customer ONT?",
            "Who prepares the detailed estimation and BOQ for access network planned events?",
            "Who handles the fiber resource allocation for new LTE and CDMA base stations?",
            "What are the installation guidelines for connecting an AGW to the primary fiber access network?",
            "How is QRadar configured to collect logs from our core routers and firewalls?",
        ],
    },
    "legal": {
        "display_name": "Legal",
        "description": (
            "The Legal domain manages corporate risk and contractual obligations through frameworks like "
            "the General Conditions of Contract (GCC), Special Conditions of Contract (SCC), Master "
            "Service Agreements (MSA), and Bilateral Non-Disclosure Agreements (NDAs). It handles "
            "regulatory compliance and dispute resolution involving bodies such as the SIAC, ICLP, and "
            "the Telecommunications Regulatory Commission, ensuring adherence to the Personal Data "
            "Protection Act No.09 of 2022 and the Anti-Corruption Act of 09 of 2023. Key corporate legal "
            "processes include intellectual property protection, arbitration proceedings, liability and "
            "indemnity management, and the execution of legal certifications under directives like GCEO "
            "Circular 26/2015 and 27/2015."
        ),
        "keywords": [
            "General Conditions of Contract (GCC)",
            "Special Conditions of Contract (SCC)",
            "Bilateral Non-Disclosure Agreement (NDA)",
            "Master Procurement Agreement",
            "Master Service Agreement (MSA)",
            "Service Level Agreement (SLA) penalties",
            "Power of Attorney",
            "Dispute Resolution Mechanism",
            "SIAC Arbitration",
            "UNCITRAL Arbitration Rules",
            "ICLP Sri Lanka",
            "Indemnity of Intellectual Property Rights",
            "Liability caps",
            "Liquidated Damages Formula",
            "Trademark registration",
            "Patent infringement",
            "Personal Data Protection Act No.09 of 2022",
            "Anti-Corruption Act of 09 of 2023",
            "Prevention of Money Laundering Act",
            "Financial Transaction Reporting Act No.06 of 2006",
            "Telecommunications Regulatory Commission (TRC)",
            "Consumer Affairs Authority Act No. 9 of 2003",
            "GCEO Circular No. 26/2015",
            "GCEO Circular No. 27/2015",
            "GCEO Circular No. 34/2015",
            "Legal Certification Form",
            "LGLS/FCC/002",
            "Damage to Third Party Property",
            "Force Majeure",
            "Termination for Convenience",
            "Termination for Default",
            "Termination for Insolvency",
            "Indemnity against Claims of Employees",
            "Transfer of Title",
            "Non-Solicitation clause",
            "Warranty of Title",
            "IRU Capacity Sales Agreement",
            "Franchise Teleshop Operations",
            "FCID information disclosure",
            "Legal risk management",
        ],
        "examples": [
            "Who is authorized to sign a Bilateral Non-Disclosure Agreement on behalf of the company?",
            "What is the standard exception clause for Confidential Information in our NDAs?",
            "What is the standard indemnity clause for vendors under the General Conditions of Contract (GCC)?",
            "How do we draft the Special Conditions of Contract (SCC) for software licenses?",
            "What are the standard terms for Termination for Convenience in a Master Service Agreement (MSA)?",
            "How is the limitation of liability structured in the Reciprocal Master Service Agreement?",
            "What are the regulatory requirements under the Personal Data Protection Act No.09 of 2022 for processing subscriber data?",
            "How do we ensure compliance with the Anti-Corruption Act of 09 of 2023 in our supplier contracts?",
            "How do we initiate arbitration for foreign contractors under the SIAC rules?",
            "When should a dispute be referred to the ICLP Sri Lanka versus a competent local court?",
            "What is the standard clause for the indemnity of Intellectual Property rights against patent infringement?",
            "How do we protect our trademarks and logos in a Franchise Teleshop Operations agreement?",
            "What is the required process for executing sales agreements under GCEO Circular No. 26/2015?",
            "Which external administrative authorities are permitted to request intercepted messages under GCEO Circular 34/2015?",
            "What forms are required to submit an LGLS/FCC/002 Legal Certification Form to the Chief Legal Officer?",
            "What are the drafting requirements to execute a Power of Attorney for bank negotiations?",
            "What is the legal standard for 'Damage to Third Party Property' in civil works contracts?",
            "How do we handle liquidated damages and SLA penalties in an OSP Unit Rate Contract?",
        ],
    },
    "marketing": {
        "display_name": "Marketing",
        "description": (
            "The Marketing domain focuses on managing the SLT corporate identity as defined in the "
            "Corporate Brand Guidelines Version 2012, along with overseeing brand activations, events, "
            "and sponsorship-related activities. It encompasses the end-to-end campaign and visibility "
            "management processes, including outdoor branding (hoardings, MSANs, pylons, digital "
            "displays), vehicle and premises branding, and the production and distribution of Point of "
            "Sale Materials (POSM) and promotional giveaways."
        ),
        "keywords": [
            "Corporate Brand Guidelines Version 2012",
            "Brand Activations & Events",
            "Procedure No - 01",
            "Concept paper approval",
            "Post-event evaluation",
            "Outdoor Branding",
            "Hoardings",
            "Procedure No - 02",
            "Artwork designs",
            "Brand Marketing division",
            "BM division",
            "MSANS Branding",
            "Procedure No - 03",
            "POSM Production",
            "Procedure No - 04",
            "Giveaway items",
            "Pylons Branding",
            "Procedure No - 05",
            "Vehicle Branding",
            "Procedure No - 06",
            "Premises Branding",
            "Procedure No - 07",
            "Outdoor digital display",
            "LED & TV Screen",
            "Procedure No - 08",
            "TVC",
            "Television Commercials",
            "Digital screen agencies",
            "Distribution of POSM",
            "Procedure No - 09",
            "Sponsorship-related activations",
            "Crowd pullers",
            "ESG events giveaways",
            "Product launches giveaways",
            "Corporate gifts",
            "Strategic importance of location",
            "Visibility",
            "Marketing Services Section",
            "CMO approval",
            "One Country. One Voice.",
        ],
        "examples": [
            "What is the approval process for a brand activation concept paper under Procedure No - 01?",
            "Who authorizes a brand activation or event request according to Procedure No - 01?",
            "What are the brand guidelines for utilizing the One Country One Voice tagline in the Corporate Brand Guidelines Version 2012?",
            "What are the guidelines for using the company logo on vehicle branding per the Corporate Brand Guidelines Version 2012?",
            "What is the approval process for acquiring new hoarding sites under Procedure No - 02?",
            "Who do we coordinate with to get artwork designs for outdoor hoardings from the Brand Marketing division?",
            "What is the process for submitting TVCs to digital screen agencies under Procedure No - 08?",
            "Who provides the approved TVCs for outdoor digital displays from Brand Marketing?",
            "What is the approval process for POSM production and giveaway items under Procedure No - 04?",
            "What are the guidelines for distributing POSM at sponsorship-related activations under Procedure No - 09?",
            "How do we evaluate the ROI and customer segment for ESG event giveaways in Procedure No - 09?",
            "What is the process for executing premises branding with the Marketing Services Section?",
            "Who is responsible for inspecting the quality of a pylon branding installation for Marketing Services?",
            "What is the approval process for MSAN branding quotations?",
            "What are the guidelines for ensuring the visibility and strategic importance of outdoor branding locations?",
            "Who authorizes the distribution of promotional items for product launches?",
            "What is the procedure for obtaining post-event evaluations after a brand activation?",
            "How does the user division request new artwork creation from the BM division?",
        ],
    },
    "enterprise_business": {
        "display_name": "Enterprise Business",
        "description": (
            "The Enterprise Business domain manages B2B corporate product lines including IP VPN, "
            "Internet Leased Lines (ILL), iDC hosting, managed Security Operations Centres (MSOC), "
            "and IoT platforms. Operational governance and commercial frameworks are overseen by bodies "
            "such as the Enterprise Investment Management Committee (EIMC) and the Enterprise Solutions "
            "Governance Board (ESGB), managing strategic partnerships, unit rate contracts, and "
            "enterprise service deployments. B2B portfolios also include enterprise CPE/NTU "
            "standardization, UC VoIP upgrades, and tailored digital solutions for corporate tiers like "
            "SME, MB, LB, and GI."
        ),
        "keywords": [
            "Enterprise Investment Management Committee (EIMC)",
            "Enterprise Solutions Governance Board (ESGB)",
            "Enterprise Solutions Techno Commercial Evaluation Team (ES-TCET)",
            "Managed Security Operations Centre (MSOC)",
            "IP VPN and Ethernet VPN links",
            "Internet Leased Lines (ILL)",
            "iDC hosting services and colocation",
            "DIOD lines (E1)",
            "SIP trunk monthly rentals",
            "10G fiber with geo redundancy",
            "Entgra IoT Platform",
            "Enterprise Mobility Management (EMM) Solution",
            "IBM PartnerWorld Business Program",
            "Enterprise CPE Solutions (Project No.190504)",
            "Direct Delivery Purchase (DDP) unit rate contract",
            "Cisco Routers for SLT managed Networks",
            "Enterprise Digital Lead Management System",
            "SME, MB, LB, GI corporate tiers",
            "Enterprise Services Request Form",
            "Material Standardization Committee",
            "CPE/Material Standardization Process",
            "UC upgrade of VOIP services",
            "Microsoft Skype Integration for Enterprise",
            "Datacenter co-network switches",
            "On-premise managed firewalls",
            "Revenue share model partnership",
            "Enterprise Business Development procurement",
            "Financial Feasibility Approvals (Project Appraisal)",
            "Five year managed services agreement",
            "DGM/SME Business account management",
            "Sales Implementation and Delivery Service Provisioning (DSP)",
            "Deactivation Service Ticket (DST) process",
            "Technical Feasibility assessment",
            "BPET process evaluation",
            "Grandstream WP820 enterprise IP Phones",
            "Active network switches for LAN solution",
            "iDC cloud infrastructure",
            "Customer Requirement Gathering",
            "Draft Agreement and Legal Sign-off",
        ],
        "examples": [
            "What are the standard terms for the Managed Security Operations Centre (MSOC) forensics and event correlation?",
            "What is the commercial framework for establishing an MSOC tailored for a large banking client?",
            "How do we calculate the pricing framework for a 10G fiber Internet Leased Line (ILL) with geo redundancy?",
            "What are the eligibility criteria for providing Ethernet VPN links to a corporate ATM network?",
            "What is the revenue share model for the Entgra IoT Platform deployed for enterprise facility management?",
            "How do we initiate a POC for an Enterprise Mobility Management solution using the Entgra IoT platform?",
            "What is the process to evaluate the SLT-IBM partnership under the BPET process for enterprise customers?",
            "Who approves the discount matrices when reselling IBM IT Infrastructure and Security Solutions via the PartnerWorld program?",
            "What is the governance process under the Material Standardization Committee for purchasing new enterprise CPEs and NTUs?",
            "How do we apply the DDP unit rate amendment for Cisco Routers used in SLT managed networks?",
            "What is the escalation matrix for Technical Feasibility approval when designing a corporate network solution?",
            "What are the steps for an account manager to initiate a DST in the deactivation process for a corporate client?",
            "Who approves the Enterprise Services Request Form for setting up internal corporate cloud resources?",
            "What is the pricing framework for upgrading a corporate client to a UC VOIP system with Microsoft Skype Integration?",
            "What are the standard commercial terms for SIP trunk monthly rentals and DIOD lines?",
            "What is the threshold for requiring an EIMC Stage 1 submission for a new enterprise managed service?",
            "How does the ES-TCET evaluate the CAPEX procurement of goods for enterprise product requirements?",
        ],
    },
    "consumer_business": {
        "display_name": "Consumer Business",
        "description": (
            "The Consumer Business domain focuses on B2C telecommunications products and services, "
            "including PSTN (Mega Line), ADSL, FTTH broadband, LTE mobile, and Peo TV packages "
            "(Single, Double, and Triple Play). It governs mass-market retail operations such as "
            "consumer sales dealer registrations, commission payouts, and loyalty promotions like the "
            "RAM Loyalty Offer. Additionally, it covers B2C operational frameworks including consumer "
            "pricing guidelines, pro-forma invoice collections, Late Payment Fees (LPF) for fiber "
            "customers, disconnection cancellations, and Condominium Product Tariffs for Multi-Tenant "
            "Buildings."
        ),
        "keywords": [
            "Consumer Business Sales",
            "Freelance officer commission",
            "Sales Dealer Registration",
            "Broadband New Connection ADSL",
            "MEGA LINE new connection",
            "SLT RAM Loyalty Offer",
            "Free cordless phone promo",
            "Free PEO TV signup",
            "Free extra 100GB data",
            "Fibre Late Payment Fee (LPF)",
            "Fiber Credit Class",
            "Minimum Past Due Amount",
            "FTTH Web Application leads",
            "35% Sales Dealer Commission",
            "Peo TV startup fee",
            "75% partial bill settlement",
            "SLT e-bill Service",
            "AB-Fiber Access Bearer",
            "FTTH New Connection Standard",
            "FTTH 3 Installments Plan",
            "FTTH 12 Installments Plan",
            "FTTH Migration Standard",
            "PSTN Single Play",
            "PSTN Double Play BB",
            "PSTN Triple Play",
            "Condominium Product Tariff",
            "Multi-Tenant Building (MTB) FTTH discount",
            "LTE Voice only package",
            "LTE BB Double Play",
            "FTTH Double play Peo",
            "PeoTV over LTE",
            "PeoTV Go App",
            "Videsa program",
            "M-cash/Ezy cash integration",
            "Copper-to-Fiber Migration",
            "Disconnection order cancellation",
            "Consumer compliance registration",
            "Selling CPE to Consumer Segment",
            "Pro-forma invoice initiation payment",
            "MINT CRM bill dispute",
        ],
        "examples": [
            "What is the price of the FTTH New Connection Standard package?",
            "What is the customer charge for the FTTH 3 Installments Plan?",
            "How much is the Peo TV startup fee for a new registration?",
            "What are the conditions for the SLT RAM Loyalty Offer?",
            "Who is eligible to receive the free cordless phone or the 50% discount?",
            "What is the standard dealer commission on completing an FTTH lead?",
            "How do freelance sales officers receive their monthly commission payments?",
            "What is the fixed charge for the Fibre Late Payment Fee?",
            "Which Fiber Credit Class applies to a monthly bill value of Rs. 4,500?",
            "Who is eligible for the Condominium Product Tariff?",
            "What are the discount terms for FTTH services in Multi-Tenant Buildings?",
            "What is the minimum partial bill settlement required to cancel a disconnection order?",
            "What are the rules for reinitiating a cancelled sales order without violating the pro-forma invoice?",
            "Can you explain the billing options for the FTTH 12 Installments Plan?",
            "Are customers allowed to use M-cash or Ezy cash for bill settlements?",
            "What is the process for registering a new customer for the SLT e-bill Service?",
            "What is the difference between PSTN Double Play BB and PSTN Triple Play bundles?",
            "Are LTE routers and PeoTV Set Top Boxes treated as OPEX or CAPEX when sold to consumers?",
            "How do I process a bill dispute for a home broadband customer in MINT CRM?",
            "Is the Videsa educational program available on the PeoTV platforms?",
        ],
    },
}

GENERAL_HELP_PATTERNS: tuple[str, ...] = (
    r"^\s*(hi|hello|hey|good morning|good afternoon|good evening)[!. ]*$",
    r"\b(thanks|thank you|bye|goodbye)\b",
    # "what / how can you do / help (me with)" family — covers most capability questions.
    r"\bwhat (can|do) you (do|help|offer|provide|support|handle)\b",
    r"\bwhat can you help (me )?(with|on|about)\b",
    r"\bhow can you (help|assist)\b",
    # Capability / scope phrasings
    r"\bwhat are (your|the) (capabilities|services|features|abilities|skills|areas|topics)\b",
    r"\bwhat (topics|areas|things|services|tasks) (can|do) you (help with|cover|support|handle|do)\b",
    r"\bwhat (are you|can you be) (capable of|able to do|used for)\b",
    # Identity / platform questions
    r"\bwho are you\b",
    r"\bwhat is workmate ai\b",
    r"\bhow does this work\b",
    r"\bhow do i use (this|the platform|workmate ai)\b",
    # Routing-help phrasings
    r"\bwhich agent should i use\b",
    r"\bwho handles\b",
    r"\bwhere should i ask\b",
    r"\bavailable agents\b",
    r"\bhelp me choose\b",
    r"\broute me\b",
)

VAGUE_SPECIALIST_PATTERNS: tuple[str, ...] = (
    r"^\s*help\s*\??\s*$",
    r"^\s*support\s*\??\s*$",
    r"^\s*i need help\s*\??\s*$",
    r"^\s*i need help with something\s*\??\s*$",
    r"^\s*i need assistance\s*\??\s*$",
    r"^\s*can you help me\s*\??\s*$",
    r"^\s*i have a question\s*\??\s*$",
    r"^\s*i need to ask something\s*\??\s*$",
)

CLARIFICATION_CHOICE_ALIASES: dict[str, tuple[str, ...]] = {
    "hr": ("hr", "human resources"),
    "finance": ("finance", "financial", "accounts", "accounting"),
    "admin": ("admin", "administration", "facilities"),
    "it": ("it", "information technology", "tech support", "technical support"),
    "cia": ("cia", "cia office", "chief internal auditor"),
    "network": ("network", "networks", "noc", "networking"),
    "legal": ("legal", "law", "contracts", "agreements"),
    "marketing": ("marketing", "branding", "promotions", "PR"),
    "enterprise_business": ("enterprise business", "enterprise", "corporate", "b2b", "ebu", "enterprise solutions"),
    "consumer_business": ("consumer business", "consumer", "retail", "residential", "cbu", "home"),
}

FOLLOW_UP_PATTERNS: tuple[str, ...] = (
    r"^\s*what about( that| this)?\s*\??$",
    r"^\s*how about( that| this)?\s*\??$",
    r"^\s*can i apply\s*\??$",
    r"^\s*can i do that\s*\??$",
    r"^\s*what next\s*\??$",
    r"^\s*how do i apply\s*\??$",
    r"^\s*and that\s*\??$",
    r"^\s*what else\s*\??$",
    r"^\s*how much\s*\??$",
)

# Initial tuning defaults for cosine similarity routing.
# These should be refined later using real routing logs.
STRONG_ROUTE_THRESHOLD = 0.40
LOW_CONFIDENCE_THRESHOLD = 0.25
OUT_OF_SCOPE_THRESHOLD = 0.18
MIN_ROUTE_MARGIN = 0.04
FOLLOW_UP_STICKINESS_BOOST = 0.06
SHORT_FOLLOW_UP_MAX_WORDS = 6

# Multi-specialist fan-out: when the top match is not strong enough to delegate
# alone but the runner-up is also plausible, consult both specialists in parallel
# and synthesize a single answer instead of asking the user to clarify.
MULTI_DELEGATE_SECONDARY_THRESHOLD = 0.25
MULTI_DELEGATE_MAX_AGENTS = 2

# Keyword match boost: when a query contains one of a specialist's exact keywords
# (word-boundary match, case-insensitive), add this to that specialist's cosine
# score. This corrects for profile-embedding dilution on short queries where the
# semantic model under-scores an obvious keyword hit.
KEYWORD_MATCH_BOOST = 0.12