"""
Self-or-human handler: fires when the user replies to KB search's
"1. This solves it / 2. Create a ticket / 3. I'd like to know more" question.
"""

import re
from typing import Literal

from langchain_core.messages import AIMessage

from domain.state import AgentState
from domain.helpdesk.pipeline.helpers import (
    llm,
    _message_to_text,
    _latest_user_message,
    _latest_ai_message,
    _STRONG_FOLLOWUP_QUESTION_RE,
    _looks_like_followup_question,
    _is_query_too_vague,
)
from domain.helpdesk.prompts import (
    SELF_OR_HUMAN_TICKET_SYSTEM_PROMPT,
    SELF_OR_HUMAN_SELF_SYSTEM_PROMPT,
    SELF_OR_HUMAN_MORE_INFO_SYSTEM_PROMPT,
)
from services.helpdesk_tickets import create_solved_ticket


# [NODE] Fires when ticket_phase == "awaiting_self_or_human" — the user is
# replying to "1. This solves it / 2. Create a ticket". Keyword matching
# decides the branch; an LLM only generates the user-facing reply text.
async def self_or_human_handler(state: AgentState) -> dict:
    """Handle the user's choice using keyword detection + streaming LLM response.

    Keyword matching avoids streaming an internal label (SELF/TICKET) to the user.
    The user-visible reply is generated by a streaming LLM call.
    """
    user_message = _latest_user_message(state)
    user_lower = re.sub(r"[^\w\s]", "", user_message.lower()).strip()
    words = set(user_lower.split())

    ticket_signals = {
        "2",
        "no",
        "ticket",
        "support",
        "create",
        "raise",
        "human",
        "team",
        "agent",
        "help",
    }
    self_signals = {
        "1",
        "yes",
        "solved",
        "solves",
        "resolved",
        "resolves",
        "myself",
        "self",
        "own",
        "handle",
        "manage",
        "got",
        "understand",
        "ill",
    }
    # Option 3 ("I'd like to know more information") — kept as an explicit
    # signal set rather than relying on _STRONG_FOLLOWUP_QUESTION_RE below:
    # that regex's "more (info|details|about)" alternative doesn't match
    # "more information" (no \b between "info" and "rmation"), so the
    # option's own button label would otherwise fall through to "ambiguous".
    more_info_signals = {
        "3",
        "more",
        "info",
        "information",
    }

    # A genuine follow-up question must win before the keyword scan below,
    # not after — "can you help me understand why the distance causes extra
    # charges?" hits both "help" (a ticket_signal) and "understand" (a
    # self_signal), so under keyword-matching alone it looks like a clear
    # answer and never reaches the ambiguous-only follow-up check further
    # down, silently creating an unwanted ticket instead of answering the
    # question. Checking this first fixes that regardless of which
    # keywords the question happens to contain.
    if _STRONG_FOLLOWUP_QUESTION_RE.search(user_message):
        print(
            "[self_or_human_handler] follow-up question detected (strong signal, "
            "overriding any keyword hits) → routing back to a fresh KB search"
        )
        return {
            "helpdesk_ticket_phase": "",
            "helpdesk_research_phase": "no_solved_match",
            "helpdesk_original_query": user_message,
            "helpdesk_retry_count": 0,
        }

    wants_ticket = bool(words & ticket_signals)
    wants_self = bool(words & self_signals) and not wants_ticket
    wants_more_info = (
        bool(words & more_info_signals) and not wants_ticket and not wants_self
    )
    ambiguous = not wants_ticket and not wants_self and not wants_more_info

    print(
        f"[self_or_human_handler] wants_ticket={wants_ticket} wants_self={wants_self} "
        f"wants_more_info={wants_more_info} ambiguous={ambiguous}"
    )

    if wants_more_info:
        print(
            "[self_or_human_handler] user chose option 3 (know more) → "
            "asking what topic, then awaiting a fresh KB query"
        )
        response = await llm.ainvoke([
            {"role": "system", "content": SELF_OR_HUMAN_MORE_INFO_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ])
        return {
            "messages": [AIMessage(content=_message_to_text(response))],
            # Reuses the same phase kb_search.py's vague-query pre-check
            # uses — research_agent's existing continuation branch for it
            # already forwards the user's NEXT reply to kb_search_agent as
            # a fresh KB query, so no new phase/routing is needed here.
            "helpdesk_ticket_phase": "awaiting_retry_clarification",
            "helpdesk_retry_count": 0,
        }

    if ambiguous and _looks_like_followup_question(user_message):
        print(
            "[self_or_human_handler] follow-up question detected → "
            "routing back to a fresh KB search"
        )
        return {
            "helpdesk_ticket_phase": "",
            "helpdesk_research_phase": "no_solved_match",
            "helpdesk_original_query": user_message,
            "helpdesk_retry_count": 0,
        }

    if ambiguous:
        retry_count = state.get("helpdesk_retry_count", 0)
        if retry_count < 2:
            print(
                "[self_or_human_handler] unrecognized reply "
                f"(attempt {retry_count + 1}) → re-prompting for 1/2/3 choice"
            )
            return {
                "messages": [AIMessage(content=(
                    "Sorry, I didn't quite catch that. Please reply with:\n"
                    "1. Yes, this solves my issue\n"
                    "2. No, please create a support ticket for further help\n"
                    "3. I'd like to know more information"
                ))],
                "helpdesk_ticket_phase": "awaiting_self_or_human",
                "helpdesk_retry_count": retry_count + 1,
            }
        print(
            "[self_or_human_handler] unrecognized reply after max retries "
            "→ defaulting to ticket creation"
        )

    if wants_ticket or ambiguous:
        response = await llm.ainvoke([
            {"role": "system", "content": SELF_OR_HUMAN_TICKET_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ])
        result = {
            "messages": [AIMessage(content=_message_to_text(response))],
            "helpdesk_ticket_phase": "creating_ticket",
            "helpdesk_retry_count": 0,
        }
        # Refresh helpdesk_original_query to whatever the user just said —
        # this was missing entirely (the other two return branches above
        # both already set it), so draft_ticket() would classify/gate on
        # the STALE query from before the KB search's "1/2" question
        # instead of the real issue description the user gave here. Found
        # live 2026-08-11: replying "1"/"2"-plus-detail after a KB answer
        # left draft_ticket()'s Message Analyzer gate looking at the
        # original short/vague query and asking for detail the user had
        # already just given. Guarded by _is_query_too_vague so a bare "2"
        # reply doesn't overwrite a perfectly good earlier description
        # with nothing useful.
        if not _is_query_too_vague(user_message):
            result["helpdesk_original_query"] = user_message
        return result

    # User confirmed the KB answer resolved their issue without a ticket —
    # persist it as a solved ticket so research_agent's solved-ticket search
    # can shortcut straight to it next time the same question comes up,
    # instead of falling through to a fresh KB search every time. Only
    # reached from the KB path (kb_search_agent's "Would you like to: 1/2"
    # question) — the satisfaction_handler path for an already-solved-ticket
    # match never routes here, so this can't create duplicate entries for
    # answers that were already sourced from solved_helpdesk_tickets.
    original_query = state.get("helpdesk_original_query", "") or _latest_user_message(
        state
    )
    kb_answer = _latest_ai_message(state)
    choice_prompt_idx = kb_answer.lower().find("would you like to")
    if choice_prompt_idx != -1:
        kb_answer = kb_answer[:choice_prompt_idx].strip()

    if original_query and kb_answer:
        try:
            create_solved_ticket(requirements=original_query, answer=kb_answer)
            print(
                f"[self_or_human_handler] saved solved ticket: "
                f"query={original_query[:60]!r}"
            )
        except Exception as exc:
            print(f"[self_or_human_handler] ERROR saving solved ticket: {exc}")

    response = await llm.ainvoke([
        {"role": "system", "content": SELF_OR_HUMAN_SELF_SYSTEM_PROMPT},
        {"role": "user", "content": user_message},
    ])
    return {
        "messages": [AIMessage(content=_message_to_text(response))],
        "helpdesk_ticket_phase": "",
        "helpdesk_research_phase": "",
        "helpdesk_original_query": "",
        "helpdesk_retry_count": 0,
        "helpdesk_category_clarify_count": 0,
    }


# [ROUTER] Reads self_or_human_handler's outcome: wants a ticket → check
# duplicates; asked a follow-up question instead → fresh KB search;
# chose "know more" → end and wait for the topic; self-resolved or
# re-prompted → end and wait.
def route_after_self_or_human(
    state: AgentState,
) -> Literal["check_duplicates", "kb_search_agent", "__end__"]:
    """After self_or_human_handler: ticket → check duplicates,
    follow-up question → fresh KB search, self/re-prompt/know-more → END."""
    phase = state.get("helpdesk_ticket_phase", "")
    if phase == "creating_ticket":
        print("[router] user chose ticket → checking duplicates")
        return "check_duplicates"
    if phase == "awaiting_self_or_human":
        print("[router] unrecognized reply → re-prompted, waiting for user")
        return "__end__"
    if phase == "awaiting_retry_clarification":
        print("[router] asked what to know more about → ending (awaiting reply)")
        return "__end__"
    if state.get("helpdesk_research_phase", "") == "no_solved_match":
        print("[router] follow-up question → routing to a fresh KB search")
        return "kb_search_agent"
    print("[router] user self-resolved → ending")
    return "__end__"
